name: 🐞 BUG REPORT
description: File a Bug Report
title: "[BUG]: <title>"
labels: ["bug","NEW"]
assignees:
    - Ragdata
body:

    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to contact us about this issue

    - type: checkboxes
      id: unique
      attributes:
          label: Unique Issue?
          description: Please search to ensure that this issue has not already been reported
          options:
              - label: I have searched all existing issues
                required: true

    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: Please provide an email address or GitHub Username so we can get in touch with you.
          placeholder: "eg: mail@example.com"
      validations:
          required: true

    - type: textarea
      id: details
      attributes:
          label: Issue Details
          description: Please provide a clear and succinct description the CURRENT behaviour you're experiencing
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected Behaviour
          description: Please provide a clear and succinct description the behaviour you're expecting to see
      validations:
          required: false

    - type: textarea
      id: reproduce
      attributes:
          label: Steps to Reproduce
          description: Please provide the steps we might take to replicate the issue during testing
          placeholder: |
              1. In this environment ...
              2. With this config ...
              3. Run '...'
              4. See error
      validations:
          required: false

    - type: input
      id: prevalence
      attributes:
          label: Issue Prevalence?
          description: How often do you encounter this issue?
          placeholder: "Example: Every time I open the software"
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: Version
          description: Which version of our software has the issue?
          placeholder: "eg: 0.1.0"
      validations:
          required: true

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: |
              Please describe the environment where you encounter this issue
              Examples:
                - **OS**: WSL Ubuntu 20.04
                - **PHP**: 8.1
                - **Node**: 13.14.0
                - **NPM**: 7.6.3
                - **Browser**: Firefox 107.0.1
          value: |
              - **OS**:
              - **PHP**:
              - **Node**:
              - **NPM**:
              - **Browser**:
          render: markdown

    - type: textarea
      id: further
      attributes:
          label: Further Information
          description: |
              Please provide any links, references, screenshots, or anything else which will give us more context about your issue

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
