name: 💎 CONTRIBUTION SUBMISSION
description: Contribution Submission
title: "[CONTRIBUTION]: <title>"
labels: ["contribution","NEW"]
assignees:
    - Ragdata
body:

    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to make this contribution

    - type: checkboxes
      id: unique
      attributes:
          label: Unique Contribution?
          description: Please search to ensure that this contribution has not already been submitted
          options:
              - label: I have searched all existing issues
                required: true

    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: Please provide an email address or GitHub Username so we can get in touch with you.
          placeholder: "eg: mail@example.com"
      validations:
          required: true

    - type: checkboxes
      id: type
      attributes:
          label: Type(s) of Contribution
          description: What type(s) of contribution did you / will you make? (You may select more than one)
          options:
              - label: 🔊 Audio
              - label: ♿️ Accessibility
              - label: 🐞 Bug Reports
              - label: 📝 Blog Posts
              - label: 💼 Business Development
              - label: 💻 Code
              - label: 🖋 Content
              - label: 🔣 Data
              - label: 📖 Documentation
              - label: 🎨 Design
              - label: 💡 Examples
              - label: 📋 Event Organisation
              - label: 💵 Financial
              - label: 🔍 Funding / Grant Finding
              - label: 🤔 Ideas & Planning
              - label: 🚇 Infrastructure
              - label: 🚧 Maintenance
              - label: 🧑‍🏫 Mentoring
              - label: 📦 Packaging
              - label: 🔌 Plugin / Utility Libraries
              - label: 📆 Project Management
              - label: 📣 Promotion
              - label: 💬 Answering Questions
              - label: 🔬 Research
              - label: 👀 Reviewed Pull Requests
              - label: 🛡️ Security
              - label: 🔧 Tools
              - label: 🌍 Translation
              - label: ⚠️ Tests
              - label: ✅ Tutorials
              - label: 📢 Talks
              - label: 📓 User Testing
              - label: 📹 Videos

    - type: textarea
      id: details
      attributes:
          label: Contribution Details
          description: Please provide a clear and concise description of your contribution
      validations:
          required: true

    - type: textarea
      id: further
      attributes:
          label: Further Information
          description: |
              Please provide any links, references, screenshots, or anything else which will give us more context about your issue

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
