name: 📘 DOCS ISSUE
description: File a Documentation Issue
title: "[DOCS]: <title>"
labels: ["docs","NEW"]
assignees:
    - Ragdata
body:

    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to contact us about this issue

    - type: checkboxes
      attributes:
          label: Unique Issue?
          description: Please search to ensure that this issue has not already been reported
          options:
              - label: I have searched all existing issues
                required: true

    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: Please provide an email address or GitHub Username so we can get in touch with you.
          placeholder: "eg: mail@example.com"
      validations:
          required: true

    - type: input
      id: url
      attributes:
          label: Page URL
          description: Please provide the URL of the page which contains the issue (one issue per report please)
      validations:
          required: true

    - type: textarea
      id: details
      attributes:
          label: Issue Details
          description: Please provide a clear and succinct description the issue you've identified
      validations:
          required: true

    - type: textarea
      id: further
      attributes:
          label: Further Information
          description: |
              Please provide any links, references, screenshots, or anything else which will give us more context about your issue

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
