name: 🚧 FEATURE REQUEST
description: Submit a Feature Request
title: "[REQUEST]: <title>"
labels: ["request","NEW"]
assignees:
    - Ragdata
body:

    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to make this suggestion

    - type: checkboxes
      id: unique
      attributes:
          label: Unique Issue?
          description: Please search to ensure that this feature has not already been requested
          options:
              - label: I have searched all existing issues
                required: true

    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: Please provide an email address or GitHub Username so we can get in touch with you.
          placeholder: "eg: mail@example.com"
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: Does your suggestion arise from a problem?
          description: Are you making this suggestion because of a problem you've encountered?  Please describe it clearly.
      validations:
          required: false

    - type: textarea
      id: details
      attributes:
          label: Describe the feature / solution you'd like to see
          description: Please provide a clear and concise description of what you'd like to happen
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: Please provide a clear and concise description of any alternative solutions or features you might have considered
      validations:
          required: false

    - type: textarea
      id: further
      attributes:
          label: Further Information
          description: |
              Please provide any links, references, screenshots, or anything else which will give us more context about your issue

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
